// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text           string          `json:"text" validate:"required,lte=10"`
	UserID         string          `json:"userId" validate:"required"`
	RepeatEveryDay *RepeatEveryDay `json:"repeatEveryDay"`
}

type RepeatEveryDay struct {
	Days     int    `json:"days" validate:"required,gte=1,lte=366"`
	Time     string `json:"time" validate:"required,HH:mm"`
	Timezone string `json:"timezone" validate:"required,timezone"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
